base:
  config:
    nacos:
      hostname: localhost
      port: 8848
    rocketmq:
      hostname: 192.168.230.131
      port: 9876

spring:
  application:
    name: cloud-message-producer
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    stream:
      rocketmq:
        binder:
          name-server: 192.168.230.131:9876
      bindings:
        admin-login-log-topic: {destination: admin-login-log-topic, content-type: application/json}

dubbo:
  scan:
    base-packages: com.loven.myshop.plus.cloud.message.producer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost
    port: 8848

server:
  port: 8605

management:
  endpoints:
    web:
      exposure:
        include: "*"